//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.WebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceRef.LightControlSoap")]
    public interface LightControlSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientApp.WebServiceRef.HelloWorldResponse HelloWorld(ClientApp.WebServiceRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.WebServiceRef.HelloWorldResponse> HelloWorldAsync(ClientApp.WebServiceRef.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TurnOnResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurnOn", ReplyAction="*")]
        ClientApp.WebServiceRef.TurnOnResponse TurnOn(ClientApp.WebServiceRef.TurnOnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurnOn", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.WebServiceRef.TurnOnResponse> TurnOnAsync(ClientApp.WebServiceRef.TurnOnRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TurnOffResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurnOff", ReplyAction="*")]
        ClientApp.WebServiceRef.TurnOffResponse TurnOff(ClientApp.WebServiceRef.TurnOffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TurnOff", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApp.WebServiceRef.TurnOffResponse> TurnOffAsync(ClientApp.WebServiceRef.TurnOffRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.WebServiceRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientApp.WebServiceRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.WebServiceRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientApp.WebServiceRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TurnOnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TurnOn", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.WebServiceRef.TurnOnRequestBody Body;
        
        public TurnOnRequest() {
        }
        
        public TurnOnRequest(ClientApp.WebServiceRef.TurnOnRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TurnOnRequestBody {
        
        public TurnOnRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TurnOnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TurnOnResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.WebServiceRef.TurnOnResponseBody Body;
        
        public TurnOnResponse() {
        }
        
        public TurnOnResponse(ClientApp.WebServiceRef.TurnOnResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TurnOnResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TurnOnResult;
        
        public TurnOnResponseBody() {
        }
        
        public TurnOnResponseBody(string TurnOnResult) {
            this.TurnOnResult = TurnOnResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TurnOffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TurnOff", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.WebServiceRef.TurnOffRequestBody Body;
        
        public TurnOffRequest() {
        }
        
        public TurnOffRequest(ClientApp.WebServiceRef.TurnOffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TurnOffRequestBody {
        
        public TurnOffRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TurnOffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TurnOffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApp.WebServiceRef.TurnOffResponseBody Body;
        
        public TurnOffResponse() {
        }
        
        public TurnOffResponse(ClientApp.WebServiceRef.TurnOffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TurnOffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TurnOffResult;
        
        public TurnOffResponseBody() {
        }
        
        public TurnOffResponseBody(string TurnOffResult) {
            this.TurnOffResult = TurnOffResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LightControlSoapChannel : ClientApp.WebServiceRef.LightControlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LightControlSoapClient : System.ServiceModel.ClientBase<ClientApp.WebServiceRef.LightControlSoap>, ClientApp.WebServiceRef.LightControlSoap {
        
        public LightControlSoapClient() {
        }
        
        public LightControlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LightControlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LightControlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LightControlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.WebServiceRef.HelloWorldResponse ClientApp.WebServiceRef.LightControlSoap.HelloWorld(ClientApp.WebServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientApp.WebServiceRef.HelloWorldRequest inValue = new ClientApp.WebServiceRef.HelloWorldRequest();
            inValue.Body = new ClientApp.WebServiceRef.HelloWorldRequestBody();
            ClientApp.WebServiceRef.HelloWorldResponse retVal = ((ClientApp.WebServiceRef.LightControlSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.WebServiceRef.HelloWorldResponse> ClientApp.WebServiceRef.LightControlSoap.HelloWorldAsync(ClientApp.WebServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.WebServiceRef.HelloWorldResponse> HelloWorldAsync() {
            ClientApp.WebServiceRef.HelloWorldRequest inValue = new ClientApp.WebServiceRef.HelloWorldRequest();
            inValue.Body = new ClientApp.WebServiceRef.HelloWorldRequestBody();
            return ((ClientApp.WebServiceRef.LightControlSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.WebServiceRef.TurnOnResponse ClientApp.WebServiceRef.LightControlSoap.TurnOn(ClientApp.WebServiceRef.TurnOnRequest request) {
            return base.Channel.TurnOn(request);
        }
        
        public string TurnOn() {
            ClientApp.WebServiceRef.TurnOnRequest inValue = new ClientApp.WebServiceRef.TurnOnRequest();
            inValue.Body = new ClientApp.WebServiceRef.TurnOnRequestBody();
            ClientApp.WebServiceRef.TurnOnResponse retVal = ((ClientApp.WebServiceRef.LightControlSoap)(this)).TurnOn(inValue);
            return retVal.Body.TurnOnResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.WebServiceRef.TurnOnResponse> ClientApp.WebServiceRef.LightControlSoap.TurnOnAsync(ClientApp.WebServiceRef.TurnOnRequest request) {
            return base.Channel.TurnOnAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.WebServiceRef.TurnOnResponse> TurnOnAsync() {
            ClientApp.WebServiceRef.TurnOnRequest inValue = new ClientApp.WebServiceRef.TurnOnRequest();
            inValue.Body = new ClientApp.WebServiceRef.TurnOnRequestBody();
            return ((ClientApp.WebServiceRef.LightControlSoap)(this)).TurnOnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApp.WebServiceRef.TurnOffResponse ClientApp.WebServiceRef.LightControlSoap.TurnOff(ClientApp.WebServiceRef.TurnOffRequest request) {
            return base.Channel.TurnOff(request);
        }
        
        public string TurnOff() {
            ClientApp.WebServiceRef.TurnOffRequest inValue = new ClientApp.WebServiceRef.TurnOffRequest();
            inValue.Body = new ClientApp.WebServiceRef.TurnOffRequestBody();
            ClientApp.WebServiceRef.TurnOffResponse retVal = ((ClientApp.WebServiceRef.LightControlSoap)(this)).TurnOff(inValue);
            return retVal.Body.TurnOffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApp.WebServiceRef.TurnOffResponse> ClientApp.WebServiceRef.LightControlSoap.TurnOffAsync(ClientApp.WebServiceRef.TurnOffRequest request) {
            return base.Channel.TurnOffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApp.WebServiceRef.TurnOffResponse> TurnOffAsync() {
            ClientApp.WebServiceRef.TurnOffRequest inValue = new ClientApp.WebServiceRef.TurnOffRequest();
            inValue.Body = new ClientApp.WebServiceRef.TurnOffRequestBody();
            return ((ClientApp.WebServiceRef.LightControlSoap)(this)).TurnOffAsync(inValue);
        }
    }
}
